version: '3.9'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    container_name: mongodb
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw

  mongo-express:
    image: mongo-express
    container_name: mongodashboard
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpw
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpw@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: mexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mexpress 
