version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
    - ./mysql_data:/var/lib/mysql
  