version: '3.8'
services:
  cache:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - cache:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '5540:5540'
    volumes:
      - ./data/redisinsight:/db
volumes:
  cache:
    driver: local